services: 
  web:
    image: ${DOCKER_USER}/gymapp:1.0.0
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gymapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456789
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:9.2
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=gymapp
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5

volumes:
  db_data: